name: CI/CD for Product Generator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_to_space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
         
          # Clone with a fresh directory
          rm -rf hf-space-temp
          git clone https://user:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_ID} hf-space-temp
          cd hf-space-temp
          
          # NUCLEAR OPTION: Remove everything except .git
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Copy ONLY the necessary files from backend/ to root of Space
          cp ../backend/Dockerfile ./
          cp ../backend/main.py ./
          cp ../backend/requirements.txt ./
          
          # Copy .dockerignore if it exists (optional)
          [ -f ../backend/.dockerignore ] && cp ../backend/.dockerignore ./ || true
          
          # Create the README at root level
          cat > README.md << 'EOF'
---
title: Product Description Generator
emoji: ✨
colorFrom: purple
colorTo: pink
sdk: docker
app_port: 8000
pinned: false
---

# Product Description Generator

AI-powered product description generator.

**Note:** First startup takes 5-10 minutes as AI models download (~7GB).
EOF
          
          # Show what we're about to commit
          echo "=== Files that will be pushed ==="
          ls -la
          echo ""
          echo "=== README.md content ==="
          cat README.md
          
          # Stage all changes
          git add -A
          
          # Commit everything
          git commit -m "Clean deployment from GitHub Actions: ${{ github.sha }}" || echo "No changes"
          
          # Force push to ensure clean state
          git push --force origin main
          
          # Cleanup
          cd ..
          rm -rf hf-space-temp