# This is a basic workflow to demonstrate MLOps CI/CD
name: CI/CD for Product Generator

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Define the image tag once as a job-level environment variable for reliability
    env:
      IMAGE_TAG: ${{ github.repository_owner }}/product-description-generator:${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC with Google Drive Credentials
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          DVC_GDRIVE_URL: ${{ secrets.DVC_GDRIVE_URL }}
        run: |
          dvc remote add -d gdrive "$DVC_GDRIVE_URL"
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive-creds.json
          dvc remote modify gdrive gdrive_use_service_account true
          dvc remote modify gdrive gdrive_service_account_json_file_path gdrive-creds.json

      - name: Pull DVC data
        run: dvc pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false 
          load: true 
          tags: ${{ env.IMAGE_TAG }} # Use the environment variable
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_TAG }} # Use the same environment variable
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

