# This workflow demonstrates a full MLOps CI/CD pipeline
name: CI/CD for Product Generator

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # The env block is removed from here as it will be set dynamically

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC with Google Drive Credentials
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          DVC_GDRIVE_URL: ${{ secrets.DVC_GDRIVE_URL }}
        run: |
          dvc remote add -d gdrive "$DVC_GDRIVE_URL"
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive-creds.json
          dvc remote modify gdrive gdrive_use_service_account true
          dvc remote modify gdrive gdrive_service_account_json_file_path gdrive-creds.json

      - name: Pull DVC data
        run: dvc pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # --- DEPLOYMENT STEPS START HERE ---

      # This new step converts the HF username to lowercase for the Docker tag
      - name: Set lowercase environment variables
        run: |
          echo "HF_USERNAME_LOWER=$(echo ${{ secrets.HF_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to Hugging Face Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.hf.space
          username: ${{ secrets.HF_USERNAME }}
          password: ${{ secrets.HF_TOKEN }}
      
      # Step 8: Build and Push the Docker image to Hugging Face
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true # This is the key change to enable deployment
          # This now uses the lowercase username variable
          tags: registry.hf.space/${{ env.HF_USERNAME_LOWER }}/product-description-generator:latest 
          cache-from: type=gha
          cache-to: type=gha,mode=max

