name: CI/CD for Product Generator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_to_space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
         
          # Clone with a fresh directory
          rm -rf hf-space-temp
          git clone https://user:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_ID} hf-space-temp
          cd hf-space-temp
          
          # Remove everything except .git
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Copy necessary files from backend/ to root
          cp ../backend/Dockerfile ./
          cp ../backend/main.py ./
          cp ../backend/requirements.txt ./
          
          # Create README - NOTE THE DIFFERENT EOF DELIMITER
          cat > README.md <<'EOFREADME'
          ---
          title: Product Description Generator
          emoji: ✨
          colorFrom: purple
          colorTo: pink
          sdk: docker
          app_port: 8000
          pinned: false
          ---
          
          # Product Description Generator
          
          AI-powered product description generator.
          
          **Note:** First startup takes 5-10 minutes as AI models download (~7GB).
          EOFREADME
          
          # Show what we have
          echo "=== Files in repo ==="
          ls -la
          echo ""
          echo "=== README.md content ==="
          cat README.md
          echo ""
          
          # Stage everything
          git add -A
          
          # Show what will be committed
          echo "=== Git status ==="
          git status
          
          # Commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy from GitHub Actions: ${GITHUB_SHA}"
            echo "=== Pushing to HF Space ==="
            git push --force origin main
            echo "=== Push complete ==="
          fi