# This workflow uses the robust, Git-based deployment method for HF Spaces
name: CI/CD for Product Generator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC with Google Drive Credentials
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          DVC_GDRIVE_URL: ${{ secrets.DVC_GDRIVE_URL }}
        run: |
          dvc remote add -d gdrive "$DVC_GDRIVE_URL"
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive-creds.json
          dvc remote modify gdrive gdrive_use_service_account true
          dvc remote modify gdrive gdrive_service_account_json_file_path gdrive-creds.json

      - name: Pull DVC data
        run: dvc pull

      # --- DEPLOYMENT STEP USING GIT PUSH ---
      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure git for the action
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Clone the Hugging Face Space repository into a new directory
          # The HF_SPACE_ID secret should be in the format: YourUsername/YourSpaceName
          git clone https://user:${HF_TOKEN}@huggingface.co/spaces/${{ secrets.HF_SPACE_ID }} hf-space
          
          # Navigate into the Space repo and enable Git LFS
          cd hf-space
          git lfs install
          
          # Copy the backend code and DVC-tracked models into the Space repo
          # Using rsync is more robust and handles large directories better
          rsync -av --delete ../backend/ ./
          
          # Tell Git LFS to track the large model files
          git lfs track "models/**"
          
          # Ensure the README has the correct metadata for a Docker Space
          cat > README.md << 'EOF'
---
title: Product Description Generator
emoji: ✨
colorFrom: purple
colorTo: pink
sdk: docker
app_port: 8000
pinned: false
---
EOF
          
          # Add all files to be committed (including LFS pointers)
          git add .
          
          # Commit the changes if there are any
          git diff --quiet && git diff --staged --quiet || git commit -m "Deploy from GitHub Actions: ${{ github.sha }}"
          
          # Push the changes (including LFS files) to the Hugging Face Space
          git push

